### ISSUE TITLE
Why all of your machine runs on ubuntu?

### ISSUE THREAD

**Issue by magictomagic** [roles-ansible/ansible_role_i3wm#7]
In yaml:
``` 
...
 runs-on: ubuntu-latest
...
```yaml

**Comment by DO1JLR** [comment]
The Github actions here all run on "ubuntu-latest", as they themselves spawn another container based on a dockerconainer. For example, the "[ansible-debian-latest.yml](https://github.com/roles-ansible/ansible_role_i3wm/blob/main/.github/workflows/ansible-debian-latest.yml)" calls [this](https://github.com/marketplace/actions/check-ansible-debian-latest) action.
